export const variants = [
    { " 14 ": "He is feeding the dog.", " 15 ": "Yes, he does.", " 16 ": "Yes, he is.", " 17 ": "He is a doctor." },
    { " 28 ": "Специальный вопрос к любому члену предложения.", " 30 ": "Вопрос, являющийся уточнением какого-либо утверждения.", " 32 ": "Вопрос, требующий ответа «Да» или «Нет».", " 34 ": "Вопрос, предполагающий выбор между двумя качествами, предметами или действиями." },
    { " 42 ": "have", " 45 ": "have had", " 48 ": "make", " 51 ": "had" },
    { " 56 ": "to play", " 60 ": "to smile", " 64 ": "to laugh", " 68 ": "to see" },
    { " 70 ": "При помощи суффикса «-ly» от глаголов.", " 75 ": "При помощи суффикса «-ed» от существительных.", " 80 ": "При помощи суффикса «-ing» от прилагательных.", " 85 ": "При помощи суффикса «-ly» от прилагательных." },
    { " 84 ": "lady", " 90 ": "son", " 96 ": "daughter", " 102 ": "gentleman" },
    { " 98 ": "teach – taught – taught", " 105 ": "catch – caught – caught", " 112 ": "seek – sought – sought", " 119 ": "bring – braught – braught" },
    { " 112 ": "She is a manager.", " 120 ": "She cleans the house every day.", " 128 ": "She is clean the carpet.", " 136 ": "She is playing with the bunny." },
    { " 126 ": "Действие, выраженное глаголом в Present Continuous, во всех случаях совершается постоянно или регулярно в настоящем времени.", " 135 ": "Действие совершается всегда в будущем времени.", " 144 ": "Действие уже совершено, и в предложении подчеркивается результат такого действия.", " 153 ": "Действие совершается в данный момент, или момент речи в настоящем времени." },
    { " 140 ": "to watch", " 150 ": "to be watched", " 160 ": "watch", " 170 ": "watching" },
    { " 154 ": "for laughing", " 165 ": "and laughed", " 176 ": "to laughed", " 187 ": "laughing" },
    { " 168 ": "Can I take your pencil?", " 180 ": "Must I take your pencil?", " 192 ": "Should I take your pencil?", " 204 ": "May I take your pencil?" },
    { " 182 ": "Martha never heard him spoke English.", " 195 ": "Martha never heard him to speak English.", " 208 ": "Martha never heard how he speaks English.", " 221 ": "Martha has never heard him speak English." },
    { " 196 ": "I know him four years.", " 210 ": "I have been knowing him for four years.", " 224 ": "I know him for four years.", " 238 ": "I have known him for four years." },
    { " 210 ": "tape", " 225 ": "age", " 240 ": "make", " 255 ": "map" },
    { " 224 ": "many", " 240 ": "few", " 256 ": "a few", " 272 ": "little" },
    { " 238 ": "has arrived", " 255 ": "arrived", " 272 ": "is arrived", " 289 ": "had arrived" },
    { " 252 ": "It must be that he has sold his car.", " 270 ": "He must sold his car.", " 288 ": "He should have solden his car.", " 306 ": "He must have sold his car." },
    { " 266 ": "I want that the weather will be fine.", " 285 ": "I want the weather be fine.", " 304 ": "I want the weather being fine.", " 323 ": "I want the weather to be fine." },
    { " 280 ": "What an intelligent boy is he!", " 300 ": "What the intelligent boy is he!", " 320 ": "What the intelligent boy he is!", " 340 ": "What an intelligent boy he is!" },
    { " 294 ": "Though it was nine o’clock in the evening, there were not many people in the bar.", " 315 ": "Although it is nine o’clock in the evening, there are not many people in the restaurant.", " 336 ": "It was only nine o’clock in the morning, and there were too many people in the café.", " 357 ": "Through it was eight o’clock in the morning, there weren’t many people in the pub." },
    { " 308 ": "I read magazines every day.", " 330 ": "I am reading a book.", " 352 ": "I have been reading the magazine for two hours.", " 374 ": "Все варианты подходят." },
    { " 322 ": "achieved", " 345 ": "entered", " 368 ": "reached", " 391 ": "arrived" },
    { " 336 ": "on", " 360 ": "in", " 384 ": "over", " 408 ": "up" },
    { " 350 ": "a advice", " 375 ": "an advice", " 400 ": "some advices", " 425 ": "a piece of advice" },
    { " 364 ": "what was my favourite vegetable", " 390 ": "what is my favourite vegetable", " 416 ": "what about my favourite vegetable", " 442 ": "what my favourite vegetable was" },
    { " 378 ": "in", " 405 ": "for", " 432 ": "about", " 459 ": "on" },
    { " 392 ": "would not mistake", " 420 ": "would not have been mistaken", " 448 ": "did not mistake", " 476 ": "would not have mistaken" },
    { " 406 ": "was", " 435 ": "is", " 464 ": "will be", " 493 ": "would be" },
    { " 420 ": "Which", " 450 ": "Whose", " 480 ": "Who", " 510 ": "Who's" },
    { " 434 ": "does Mr Johnson have", " 465 ": "had Mr Johnson had", " 496 ": "has Mr Johnson been having", " 527 ": "has Mr Johnson had" },
    { " 448 ": "brains", " 480 ": "decision", " 512 ": "head", " 544 ": "mind" },
    { " 462 ": "will come", " 495 ": "came", " 528 ": "was coming", " 561 ": "comes" },
    { " 476 ": "his", " 510 ": "her", " 544 ": "its", " 578 ": "their" },
    { " 490 ": "either shouldn't she", " 525 ": "she did either", " 560 ": "neither she should", " 595 ": "neither should she" },
    { " 504 ": "sured", " 540 ": "insured", " 576 ": "ensured", " 612 ": "reassured" },
    { " 518 ": "economics", " 555 ": "economy", " 592 ": "economic", " 629 ": "economical" },
    { " 532 ": "responsible", " 570 ": "respondent", " 608 ": "response", " 646 ": "responsive" },
    { " 546 ": "doing", " 585 ": "to do", " 624 ": "are doing", " 663 ": "should do" },
    { " 560 ": "acceptance", " 600 ": "entrance", " 640 ": "admittance", " 680 ": "admissions" },
    { " 574 ": "need overhauling", " 615 ": "need overhauled", " 656 ": "need to overhauling", " 697 ": "need to overhaul" },
    { " 588 ": "So am I", " 630 ": "So I like", " 672 ": "So I do", " 714 ": "So do I" },
    { " 602 ": "during", " 645 ": "in", " 688 ": "on", " 731 ": "for" },
    { " 616 ": "You will come with me tomorrow?", " 660 ": "Do you come with me tomorrow?", " 704 ": "Come you with me tomorrow?", " 748 ": "Will you come with me tomorrow?" },
    { " 630 ": "something", " 675 ": "nobody", " 720 ": "somebody", " 765 ": "anybody" },
    { " 644 ": "are spoken", " 690 ": "is speaking", " 736 ": "is spoke", " 782 ": "is spoken" },
    { " 658 ": "more old", " 705 ": "more older", " 752 ": "most older", " 799 ": "older" },
    { " 672 ": "This", " 720 ": "That", " 768 ": "These", " 816 ": "Those" },
    { " 686 ": "get up", " 735 ": "to get up", " 784 ": "to getting up", " 833 ": "getting up" },
    { " 700 ": "I have", " 750 ": "I should have", " 800 ": "I would have", " 850 ": "I had" }
]